language: ruby
rvm:
  - 2.3.7
  - 2.4.4
  - 2.5.1
before_install: gem install bundler
install:
  - bundle install
  - bundle exec rake install
before_script: "rubocop"
addons:
  srcclr: true
script: "rake spec"
after_success: "coveralls"
