branch:
  only:
    - master
language: ruby
rvm:
  - 2.3.7
  - 2.4.4
  - 2.5.1
before_install: gem install bundler
install:
  - bundle install
script: "bundle exec rake spec"
before_script: "rubocop"
addons:
  srcclr: true
after_success: "coveralls"

jobs:
  include:
    - stage: 'Integration tests'
      env: SDK=ruby
      language: python
      before_install:
        - "pip install awscli"
        - "aws s3 cp s3://optimizely-travisci-artifacts/ci/trigger_fullstack-sdk-compat.sh ci/ && chmod u+x ci/trigger_fullstack-sdk-compat.sh"
        - "ci/trigger_fullstack-sdk-compat.sh optimizely%2Ffullstack-sdk-compatibility-suite"
      install: skip
      before_script: skip
      script: skip
      after_success: skip
